// Code generated by qtc from "dagger.md.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/dagger.md.qtpl:1
package templates

//line templates/dagger.md.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/dagger.md.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/dagger.md.qtpl:1
func StreamGenerateDagger(qw422016 *qt422016.Writer, opts Opts) {
//line templates/dagger.md.qtpl:1
	qw422016.N().S(`# dagger

## Run ci on local

It will run the following step:
  - Lint Helm chart
  - Generate schema from `)
//line templates/dagger.md.qtpl:1
	qw422016.N().S("`")
//line templates/dagger.md.qtpl:1
	qw422016.N().S(`values.yaml`)
//line templates/dagger.md.qtpl:1
	qw422016.N().S("`")
//line templates/dagger.md.qtpl:1
	qw422016.N().S(`
  - Generate readme parameters from `)
//line templates/dagger.md.qtpl:1
	qw422016.N().S("`")
//line templates/dagger.md.qtpl:1
	qw422016.N().S(`values.yaml`)
//line templates/dagger.md.qtpl:1
	qw422016.N().S("`")
//line templates/dagger.md.qtpl:1
	qw422016.N().S(`


`)
//line templates/dagger.md.qtpl:1
	qw422016.N().S("`")
//line templates/dagger.md.qtpl:1
	qw422016.N().S(``)
//line templates/dagger.md.qtpl:1
	qw422016.N().S("`")
//line templates/dagger.md.qtpl:1
	qw422016.N().S(``)
//line templates/dagger.md.qtpl:1
	qw422016.N().S("`")
//line templates/dagger.md.qtpl:1
	qw422016.N().S(`bash
# When no need to get helm dependency from private registry
dagger call -m '`)
//line templates/dagger.md.qtpl:14
	qw422016.E().S(module)
//line templates/dagger.md.qtpl:14
	qw422016.N().S(`' --src . ci export --path .

# When need to get helm dependency from private registry
dagger call -m '`)
//line templates/dagger.md.qtpl:17
	qw422016.E().S(module)
//line templates/dagger.md.qtpl:17
	qw422016.N().S(`' --src . ci --registry `)
//line templates/dagger.md.qtpl:17
	qw422016.E().S(opts.Registry)
//line templates/dagger.md.qtpl:17
	qw422016.N().S(` --registry-username env:SU_USERNAME --registry-password env:SU_PASSWORD -- export --path .
`)
//line templates/dagger.md.qtpl:17
	qw422016.N().S("`")
//line templates/dagger.md.qtpl:17
	qw422016.N().S(``)
//line templates/dagger.md.qtpl:17
	qw422016.N().S("`")
//line templates/dagger.md.qtpl:17
	qw422016.N().S(``)
//line templates/dagger.md.qtpl:17
	qw422016.N().S("`")
//line templates/dagger.md.qtpl:17
	qw422016.N().S(`

`)
//line templates/dagger.md.qtpl:20
}

//line templates/dagger.md.qtpl:20
func WriteGenerateDagger(qq422016 qtio422016.Writer, opts Opts) {
//line templates/dagger.md.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/dagger.md.qtpl:20
	StreamGenerateDagger(qw422016, opts)
//line templates/dagger.md.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line templates/dagger.md.qtpl:20
}

//line templates/dagger.md.qtpl:20
func GenerateDagger(opts Opts) string {
//line templates/dagger.md.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/dagger.md.qtpl:20
	WriteGenerateDagger(qb422016, opts)
//line templates/dagger.md.qtpl:20
	qs422016 := string(qb422016.B)
//line templates/dagger.md.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/dagger.md.qtpl:20
	return qs422016
//line templates/dagger.md.qtpl:20
}
